### ISSUE TITLE
What is the version of Unity you use?

### ISSUE THREAD

**Issue by Firesuiry** [kaiyunxue/AzerothAllStar#1]
I want to run it on my computer to have a try HHH

**Comment by kaiyunxue** [comment]
I use the Unity 2017.2.0f3 (64-bit). But you can not run the project
because I've insulated some models from the project due to the copyright.
But I can send you the .exe demo to you. Or you can watch the youtube video:
https://www.youtube.com/channel/UCaj6BszBKTSUH24c0zn8R5g?view_as=subscriber

Firesuiry <notifications@github.com> 于2018年10月9日周二 上午12:28写道：

**Comment by Firesuiry** [comment]
please send me the demo.
my address is 4690734@qq.com
thank you.
